version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          command: yarn
      - run:
          command: yarn start:axe
      - run:
          command: yarn start:name
